# Site
title: NANA bootcamp
subtitle: an imersive training in wearables tech

# URL
url: http://bootcamp.nana-kit.com
baseurl: /
permalink: :title/
include: ['_pages']

# Build settings
markdown: kramdown
port: 4448
future: true

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"